Repository nics-tw/petsard, pull requests merged in 2025-04, with the labels that each got.

#713 chore: fix project version, requirements no emit project, and upgrade…
  doc_site/go.mod
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: bug, dependencies

#738 chore(ci): config update
  .github/workflows/pages.yaml
Labels: ci

#740 chore: update dependency for security and SBOM alert
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#742 chore: update dependency for security and SBOM alert
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#743 chore: ver 1.2.2 release
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#751 fix: duplicated code caused by merge conflicts
  petsard/evaluator/describer.py
  petsard/evaluator/evaluator.py
  petsard/evaluator/stats.py
  petsard/operator.py
Labels: bug
